# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: private_chat.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12private_chat.proto\"E\n\x0e\x43onnectRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x12\n\nip_address\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"3\n\x0f\x43onnectResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\x11\x44isconnectRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"C\n\x07Message\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x14\n\x0crecipient_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"@\n\x15ReceiveMessageRequest\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x14\n\x0crecipient_id\x18\x02 \x01(\t\"Z\n\x16ReceiveMessageResponse\x12\x1b\n\x07message\x18\x01 \x01(\x0b\x32\x08.MessageH\x00\x12\x17\n\x05\x65mpty\x18\x02 \x01(\x0b\x32\x06.EmptyH\x00\x42\n\n\x08response\"\x07\n\x05\x45mpty2\xd1\x01\n\x0bPrivateChat\x12.\n\x07\x43onnect\x12\x0f.ConnectRequest\x1a\x10.ConnectResponse\"\x00\x12*\n\nDisconnect\x12\x12.DisconnectRequest\x1a\x06.Empty\"\x00\x12!\n\x0bSendMessage\x12\x08.Message\x1a\x06.Empty\"\x00\x12\x43\n\x0eReceiveMessage\x12\x16.ReceiveMessageRequest\x1a\x17.ReceiveMessageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'private_chat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONNECTREQUEST']._serialized_start=22
  _globals['_CONNECTREQUEST']._serialized_end=91
  _globals['_CONNECTRESPONSE']._serialized_start=93
  _globals['_CONNECTRESPONSE']._serialized_end=144
  _globals['_DISCONNECTREQUEST']._serialized_start=146
  _globals['_DISCONNECTREQUEST']._serialized_end=184
  _globals['_MESSAGE']._serialized_start=186
  _globals['_MESSAGE']._serialized_end=253
  _globals['_RECEIVEMESSAGEREQUEST']._serialized_start=255
  _globals['_RECEIVEMESSAGEREQUEST']._serialized_end=319
  _globals['_RECEIVEMESSAGERESPONSE']._serialized_start=321
  _globals['_RECEIVEMESSAGERESPONSE']._serialized_end=411
  _globals['_EMPTY']._serialized_start=413
  _globals['_EMPTY']._serialized_end=420
  _globals['_PRIVATECHAT']._serialized_start=423
  _globals['_PRIVATECHAT']._serialized_end=632
# @@protoc_insertion_point(module_scope)
